### ISSUE TITLE
I encapsulated it too

### ISSUE THREAD

**Issue by yandongCoder** [maxklenk/angular-circular-navigation#3]
I encapsulated it too using same tutorial by Sara Soueidan ; P 

![image](https://cloud.githubusercontent.com/assets/2842917/19303117/f9efa02c-9099-11e6-8a41-8fd292c2647b.png)
[https://github.com/yandongCoder/circular-menu](url)

**Comment by maxklenk** [comment]
Nice, looks good. Great you made it framework independent and even without jQuery.
